CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
entra_object_id CHAR(36) NULL,
name VARCHAR(120) NOT NULL,
email VARCHAR(180) NOT NULL UNIQUE,
avatar VARCHAR(255) NULL,
active TINYINT(1) NOT NULL DEFAULT 1,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;