CREATE TABLE IF NOT EXISTS operation_history (
id INT AUTO_INCREMENT PRIMARY KEY,
operation_id INT NOT NULL,
action VARCHAR(40) NOT NULL,
notes TEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_history_operation FOREIGN KEY (operation_id) REFERENCES operations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;